config/routes.rb
Stagercms::Application.routes.draw do
  devise_for :users

  mount Ckeditor::Engine => '/ckeditor'

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :news
  resources :static_page, :path => 'page'

  root :to => 'application#index'
  
  match "/news/:id" => "application#news_page", :as => 'new'
  match '/news' => 'application#newses', :as => 'newses'

  scope "(:locale)", :locale => /en|ru/ do

  end

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
  include Ckeditor::Backend::Paperclip
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  has_attached_file :data,
                    :url => "/ckeditor_assets/attachments/:id/:filename",
                    :path => ":rails_root/public/ckeditor_assets/attachments/:id/:filename"
  
  validates_attachment_size :data, :less_than => 100.megabytes
  validates_attachment_presence :data
	
	def url_thumb
	  @url_thumb ||= Ckeditor::Utils.filethumb(filename)
	end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  has_attached_file :data,
                    :url  => "/ckeditor_assets/pictures/:id/:style_:basename.:extension",
                    :path => ":rails_root/public/ckeditor_assets/pictures/:id/:style_:basename.:extension",
	                  :styles => { :content => '800>', :thumb => '118x100#' }
	
	validates_attachment_size :data, :less_than => 2.megabytes
	validates_attachment_presence :data
	
	def url_content
	  url(:content)
	end
end

app/models/menu_item.rb
class MenuItem < ActiveRecord::Base

	scope :ordering, order('position ASC')

  belongs_to :static_page
  attr_accessible :position, :status, :title, :static_page_id
end

app/models/new.rb
class New < ActiveRecord::Base

	scope :moderated, where(:status => true, :favourite => false).order('created_at DESC')
	scope :favourite, where(:status => true, :favourite => true)
	scope :recent, where(:status => true, :favourite => false).limit(6).order("created_at DESC")

  belongs_to :user
  accepts_nested_attributes_for :user
  attr_accessible :favourite, :content_full, :content_small, :status, :title, :user_id, :user
  validates :title, :length => {:minimum => 10}
  validates :content_full, :length => {:minimum => 10}
  validates :content_small, :length => {:minimum => 10}
end

app/models/static_page.rb
class StaticPage < ActiveRecord::Base
  attr_accessible :content, :status, :title
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, :authentication_keys => [:nickname]

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :role
	has_many :news
	has_attached_file :avatar
	attr_accessible :avatar, :email, :fio, :nickname, :password, :skype
  validates :nickname, :uniqueness => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :set_locale
  before_filter :set_variables
  require 'open-uri'
  require 'nokogiri'

  def index
    # add_breadcrumb I18n.t("breadcrumbs.home"), :root_path
    @title = t('titles.home')
  	@news = New.favourite
  end

  def set_variables
  	@menu_items_all = MenuItem.ordering
  end

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
    # I18n.locale = params[:locale] || 'ru'
    add_breadcrumb I18n.t("breadcrumbs.home"), :root_path
  end

end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  # add_breadcrumb I18n.t("breadcrumbs.home"), :root_path

  before_filter :find_new, :only => [:show, :destroy, :edit, :update]

	add_breadcrumb I18n.t("breadcrumbs.news"), :news_index_path
	def index
		@title = t('titles.news')
		@news = New.moderated.page(params[:page]).per(5)
	end

	def show				
		add_breadcrumb @new.title, news_path(@new)
	end

	def new
		if current_user.nil? || !current_user.role
			redirect_to news_index_path
		else
			add_breadcrumb t('breadcrumbs.addnew'), new_news_path
			@new = New.new
		end
	end

	def create
		@new = New.new(params['new'])
		@new.user = current_user
		if @new.save
			@new = New.new
		end
		render :new
	end

	def destroy
		if !current_user.nil? && current_user.role
			@new.destroy
			redirect_to news_index_path
		else
			redirect_to news_path(@new)
		end
	end

	def edit
		add_breadcrumb @new.title, news_path(@new)
		add_breadcrumb t('breadcrumbs.editnew'), edit_news_path
		redirect_to news_path(@new) if current_user.nil? || !current_user.role
	end

	def update		
		@new.update_attributes(params[:new])
		redirect_to news_path(@new)
	end

	private

	def find_new
		@new = New.find(params[:id])
	end
end

app/controllers/static_page_controller.rb
class StaticPageController < ApplicationController
  # add_breadcrumb I18n.t("breadcrumbs.home"), :root_path
	def show
		@title = StaticPage.find(params['id']).title
		@static_page = StaticPage.find(params['id'])
		add_breadcrumb @static_page.title, static_page_path[@static_page.title]
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def title
		t_base = t("titles.base")
		t_separator = "|"
		if @title.nil?
			t_base
		else
			"#{@title} #{t_separator} #{t_base}"
		end
	end

	def random
		@random_news = New.moderated.find(:first, :offset => rand(New.moderated.count))
		if !@random_news.nil?
			render :partial => "modules/random", random_news: @random_news
		end
	end

	def copyright
		render :partial => "modules/copy"
	end

	def recent
		@recent_news = New.recent
		# result = @recent_news.content_full.scan(/<img[^>]+/i)
		render :partial => "modules/recent", recent_news: @recent_news
	end

	def logout
		render :partial => "modules/logout"
	end

	def login
		render :partial => "modules/login"
	end
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/static_page_helper.rb
module StaticPageHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/_menu_item.html.haml
-@menu_items.each do |menu_item|
	%div= link_to menu_item.title, static_page_path(menu_item.static_page)

app/views/application/_new_index_item.html.haml
%div.content640
	%div.news_list#news{ id: new.id }
		%h3= new.title
		%div= raw new.content_full

app/views/application/index.html.haml
-@news.each do |new|
	= render 'new_index_item', new: new
= logout
= login
= random
= recent

app/views/layouts/application.html.haml
!!!
%html
	%head
		%title 
			= title
		%meta{:charset => "utf-8"}
		= stylesheet_link_tag "application", :media => "all"
		= javascript_include_tag 'application'
		= csrf_meta_tags
	%body
		%div#wrapper
			%h1 StagerCMS

			%div.navbar
				%div.navbar-inner
					%div.brand Main Menu
					%ul.nav
						%li= link_to t('breadcrumbs.home'), root_path
						%li= link_to t('breadcrumbs.news'), newses_path
						-@menu_items_all.each do |menu_item|
							%li= link_to menu_item.title, static_page_path(menu_item.static_page)
			%div
				= render_breadcrumbs
			= yield
			.clear
			= raw copyright

app/views/modules/_copy.html.haml
%center
	%h6
		Copyright &copy; 2012, Stanislav Gernyak

app/views/modules/_login.html.haml
- if !user_signed_in?
	.raleted3
		.mod_raleted_title
			= t('modules.login.title')
		= link_to t('modules.login.link_title'), user_session_path
		или
		= link_to t('modules.login.reg_link_title'), new_user_registration_path

app/views/modules/_logout.html.haml
- if user_signed_in?
	.raleted3
		.relative
			.mod_raleted_title
				= t('modules.logout.title')

			%table
				%tr
					%td{:style => 'vertical-align:top;'}
						%img{src: current_user.avatar, class: 'avatar_img'}
					%td{:style => 'vertical-align:top;'}
						Здравствуйте, 
						%b
							= current_user.nickname
						!
						%div
							Группа: 
							%b= current_user.role? ? "Модератор" : "Пользователь"

						%div
							Последний визит
							%b
								= current_user.last_sign_in_at.in_time_zone('Kyiv').strftime("%m.%d.%Y %H:%M")

						%div
							- if current_user.role == true
								= link_to t('modules.logout.addnew'), new_news_path, :method => :get
						%div
							= link_to t('modules.logout.out'), destroy_user_session_path, :method=> "delete"

app/views/modules/_random.html.haml
.raleted3
	.mod_raleted_title
		= t('modules.random')
	= link_to @random_news.title, new_path(@random_news['id'])
	%div
	= raw @random_news.content_small.gsub!(/(<[^>]*>)|\n|\t/, "")

app/views/modules/_recent.html.haml
-@i = 0
.raleted3
	.related2
		.mod_raleted_title
			= t('modules.recent')

		-@recent_news.each do |new|
			- doc = Nokogiri::HTML(new.content_full)
			- result32 = doc.search('img').first;
			- if result32
				- result3 = doc.search('img').first['src'];

			- new.content_small.gsub!(/(<[^>]*>)|\n|\t/, "") 

			%div.recent_new#recent_new{ id: @i }
				%img{:src => result3, :class => "img_l_r"}
				%div.link
					= link_to new.title, new_path(new['id'])
				/ = raw new.content_small
				-@i = @i+1

app/views/news/_new_item.html.haml
%div.news_list#news{ id: new.id }
	%h4= link_to new.title, new_path(new['id'])
	 
	%h6
		= distance_of_time_in_words_to_now(new.created_at, false)
		назад
		by
		= new.user.nickname
		
	%div= raw new.content_small
	%hr

app/views/news/edit.html.haml
%h3
	Редактирование новости

= form_for @new, :url => news_path, :method => :put, :action => :update do |f|
	-if @new.errors.any?
		.alert.alert-error
			%b
				Возникло
				= pluralize(@new.errors.count, "ошибка", "ошибки")
				во время добавления новости в БД!
			- @new.errors.full_messages.each do |msg|
				%li
					= msg

	%div= f.label :title, "Название:"
	%div= f.text_field :title

	%div= f.label :content_small, 'Краткий текст материала'
	%div= f.text_area :content_small, :class => "ckeditor"

	%div= f.label :content_full, 'Полный текст материала'
	%div= f.text_area :content_full, :class => "ckeditor"

	%div
		= f.check_box :status, :class => 'fl_l'
		= f.label :status, 'Новость активна?'

	%div
		= f.check_box :favourite, :class => 'fl_l'
		= f.label :favourite, 'Отображать на главной?'

	%div= f.submit 'Добавить'

app/views/news/index.html.haml
%h3 Новости
-@news.each do |new|
	= render 'new_item', new: new
= paginate @news

app/views/news/new.html.haml
%h3
	Добавить новость

= form_for @new, :url => news_index_path do |f|
	/ %div= f.error_messages
	-if @new.errors.any?
		.alert.alert-error
			%b
				Возникло
				= pluralize(@new.errors.count, "ошибка", "ошибки")
				во время добавления новости в БД!
			- @new.errors.full_messages.each do |msg|
				%li
					= msg

	%div= f.label :title, "Название:"
	%div= f.text_field :title

	%div= f.label :content_small, 'Краткий текст материала'
	%div= f.text_area :content_small, :class => "ckeditor"

	%div= f.label :content_full, 'Полный текст материала'
	%div= f.text_area :content_full, :class => "ckeditor"

	%div
		= f.check_box :status, :class => 'fl_l'
		= f.label :status, 'Новость активна?'

	%div
		= f.check_box :favourite, :class => 'fl_l'
		= f.label :favourite, 'Отображать на главной?'

	%div= f.submit 'Добавить'

app/views/news/show.html.haml
%h3= @new.title
- if !current_user.nil? && current_user.role
	%div{:style => 'margin:0 0 10px 0;'}
		[
		= link_to 'Удалить', news_path[@new.id], :action => :destory, :method => :delete, :confirm => "Вы действительно хотите удалить новость ''#{@new.title}''? Данное действие необратимо!"
		|
		= link_to 'Редактировать', edit_news_path, :action => :edit, :method => :get
		]
%div= raw @new.content_full

app/views/static_page/show.html.haml
%h3= @static_page.title
= raw @static_page.content